[package]
name = "braindump"
version = "0.2.0"
edition = "2024"

[[bin]]
name = "bd"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
home = "0.5"
serde = { version = "1", features = ["derive"] }
tempfile = "3"
toml = "0.8"

[dev-dependencies]
assert_cmd = "2"
expectrl = "0.9.0"
predicates = "3"
tempfile = "3"
